name: Deploy documentation to gh-pages

on:
  push:
    branches: [ master ]
# for testing
  pull_request:
    branches:
      - master


jobs:
  deploy-doc:
    runs-on: ubuntu-20.04
    steps:
      - name: Prepare directories
        run: |
          mkdir -p build/
      - name: Checkout remote head
        uses: actions/checkout@master
      - name: Configure Doc
        run: |
          cd build/
          cmake ../Radium-Engine/doc -DCMAKE_EXECUTE_PROCESS_COMMAND_ECHO=STDOUT
          cat Doxyfile.RadiumDoc
      - name: Build Doc
        uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: 'build/'
          doxyfile-path: 'Doxyfile.RadiumDoc'
#      - name: Deploy Doc
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
#          publish_dir: 'build/Radium-Engine/html'
