name: Pull request history validation

on: pull_request

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Check up to date linear history, without merges
      uses: skx/github-action-tester@master
      with:
        script: scripts/is-history-pr-compatible.sh
