name: Guideline Checks

on: [pull_request]

jobs:
  hitory:
    name: Check linear history
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          # checkout branch head instead of merge commit to have the potientially commited change from formatter
          ref: ${{  github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Check up to date linear history, without merges
        uses: skx/github-action-tester@master
        with:
          script: scripts/is-history-pr-compatible.sh
  format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - name: Check coding style
        id: format-check
        uses: DoozyX/clang-format-lint-action@v0.6
        with:
          source: '.'
          exclude: './tests/external ./src/Core/external ./src/Engine/external ./src/IO/external'
          extensions: 'hpp,inl,cpp'
          clangFormatVersion: 9
          style: file
      - name: In case of failure
        if: ${{ failure() }}
        run: |
          echo "CHECK FAILED, hint: force push your branch on IRIT-STROM/formatter for automatic formating. Then fetch/hard reset your branch"
          echo "git branch -D formatter"
          echo "git switch -c formatter"
          echo "# ensure you have the .github/workflows/formatter.yml file, if not add it to your branch"
          echo "git push -f --set-upstream origin formatter"
          echo "# wait for git action to finish"
          echo "git pull origin"
          echo "git checkout  ${{  github.head_ref }}"
          echo "git reset --hard formatter"
          echo "git push ${{ github.event.pull_request.head.repo.full_name }}"
